-- MeshGhost — Pokémon Emerald: spawn test 1 (FIRST WRITE TO GAME RAM ON THIS ADAPTER)
--
-- WHAT THIS DOES
-- Creates one extra character in the overworld, two tiles to the LEFT of the player, by writing
-- a synthetic object event and its sprite, then asks the engine to walk it one tile. Emerald's
-- own engine draws, animates and moves it; this script contains no drawing code and no
-- animation code. It is the Emerald equivalent of Crystal's spawn_test series.
--
-- WRITES. Gated by the spawn ADR (agent_docs/architecture.md, 2026-08-18, extending the
-- 2026-08-17 Crystal ADR). Live RAM only -- no save is written, nothing is persisted, and a
-- reset undoes all of it. Every precondition below must hold or the script refuses to write.
--
-- WHY IT IS BUILT THIS WAY (each point cost a live test on Crystal, or a decomp read here)
--
--   * The OBJECT EVENT is synthesised from scratch, not copied from an NPC. Emerald's own
--     InitObjectEventStateFromTemplate (event_object_movement.c:1287) zeroes the struct and then
--     sets an enumerable field list, so the exact write set is known rather than guessed -- and
--     copying a live NPC would drag along its localId, movement range and trainer data.
--
--   * The SPRITE is copied from the PLAYER's sprite, then patched. A sprite holds four ROM
--     pointers (anims, images, affineAnims, template) that cannot be synthesised from Lua, only
--     copied -- and copying the PLAYER's means the ghost looks like the player, in the correct
--     gender, using a palette that is already loaded on every map by construction (the player's
--     graphics are resident everywhere). Same reasoning as Crystal's "borrow the player's
--     sprite" step, arrived at there the hard way.
--
--   * The sprite's CALLBACK is replaced with MovementType_None. In Emerald the sprite callback
--     IS the movement-type driver, so copying the player's callback (MovementType_Player) would
--     hand our ghost to the input system, and an NPC's (e.g. MovementType_FaceDirection) would
--     give it that NPC's autonomous behaviour. MovementType_None is generated by
--     movement_type_empty_callback (event_object_movement.c:2563), which still calls
--     UpdateObjectEventCurrentMovement -- so the ghost has NO autonomous movement of its own,
--     yet held movements we request are still played out in full by the engine. That is exactly
--     the shape a ghost needs, and it is why no other movement type will do.
--
--   * The sprite's x/y are COMPUTED, never copied. GetMapCoordsFromSpritePos
--     (event_object_movement.c:4793) plus TrySetupObjectEventSprite's own +8 / +16+centerToCorner
--     adjustment. Copying a template's screen position is what put Crystal's first ghost off the
--     bottom of the screen while the engine drove it perfectly.
--
--   * Movement is a HELD MOVEMENT, not a coordinate write. ObjectEventSetHeldMovement
--     (event_object_movement.c:4870) is three fields plus a sprite counter reset; the engine then
--     plays out the whole tile -- animation, sub-tile sliding and the coordinate update.
--
-- ADDRESSES: our own make-compare-verified pokeemerald build. Field offsets are the /*0xNN*/
-- comments in include/global.fieldmap.h and include/sprite.h. Nothing here is recalled.
--
-- HOW TO RUN
--   Attached via dev-scripts/bizhawk-dev-loader.lua, or opened directly in the Lua Console.
--   Be in the overworld, standing still, with at least one tile of clear ground to your left.
--   The script counts down out loud before it writes; there is no moment to hit.

local OBJECT_EVENTS_COUNT = 16
local OBJECTEVENT_SIZE = 0x24
local MAX_SPRITES = 64
local SPRITE_SIZE = 0x44
local MAP_OFFSET = 7 -- object event coords are map coords + MAP_OFFSET (confirmed live: player
                     -- at pos (2,1) had currentCoords (9,8))

local GOBJECTEVENTS_ADDR = 0x02037350
local GPLAYERAVATAR_ADDR = 0x02037590
local GSPRITES_ADDR = 0x02020630
local GSAVEBLOCK1PTR_ADDR = 0x03005d8c
local GMAIN_CALLBACK2_ADDR = 0x030022c4
local CB2_OVERWORLD_ADDR = 0x08085e5c
local CB2_OVERWORLD_ARCHIPELAGO_ADDR = 0x080867f1

-- pokeemerald.sym: gFieldCamera 03005dd0 (struct CameraObject, x at +0x10, y at +0x14),
-- gTotalCameraPixelOffsetY 03005de8, gTotalCameraPixelOffsetX 03005dec.
local GFIELDCAMERA_X_ADDR = 0x03005de0
local GFIELDCAMERA_Y_ADDR = 0x03005de4
local GTOTALCAMERAPIXELOFFSETY_ADDR = 0x03005de8
local GTOTALCAMERAPIXELOFFSETX_ADDR = 0x03005dec

-- pokeemerald.sym: MovementType_None 0808f3e0. +1 selects Thumb, which is how every callback
-- pointer in the live dump reads (MovementType_Player showed as 0x0808A999 for 0808a998).
local MOVEMENTTYPE_NONE_CB = 0x0808f3e0 + 1

-- Sprite tile allocation. A sprite whose images are a frame list (not a sheet) owns a range of
-- OBJ VRAM tiles, and the engine DMAs the current animation frame into THAT range whenever the
-- frame changes (RequestSpriteFrameImageCopy, sprite.c:802, called from the anim code with
-- sprite->oam.tileNum). So a sprite copied from the player points at the PLAYER's tiles and
-- therefore displays whatever frame the player is currently in -- which is exactly what was seen
-- live: a ghost that mirrored the player's facing. Giving the ghost its own tile range makes the
-- engine fill it with the ghost's own frames, for free and with no drawing code.
--   sSpriteTileAllocBitmap  02021b3c, 0x80 bytes = TOTAL_OBJ_TILE_COUNT (1024) bits
--   gReservedSpriteTileCount 02021b3a (u16) -- allocation starts above the reserved region
--   gObjectEventGraphicsInfoPointers 08505620 -- [graphicsId] -> ObjectEventGraphicsInfo*,
--     whose `size` (u16 at +0x06) is the byte size of one frame; TILE_SIZE_4BPP is 32.
local SSPRITETILEALLOCBITMAP_ADDR = 0x02021b3c
local GRESERVEDSPRITETILECOUNT_ADDR = 0x02021b3a
local GOBJECTEVENTGRAPHICSINFOPOINTERS_ADDR = 0x08505620
local TOTAL_OBJ_TILE_COUNT = 1024
local TILE_SIZE_4BPP = 32

local MOVEMENT_TYPE_NONE = 0x00
local DIR_SOUTH = 1
local MOVEMENT_ACTION_WALK_NORMAL_DOWN = 0x08
local MOVEMENT_ACTION_WALK_NORMAL_LEFT = 0x0a

-- Facing without stepping. Emerald has a real ANIM_STD_FACE_EAST -- east is NOT drawn as a
-- flipped west here at the animation-table level (sFaceDirectionAnimNums,
-- event_object_movement.c:715) -- so all four directions should be reachable the same way, and
-- the cycle phase below tests exactly that rather than reasoning about it.
local FACE_ACTIONS = {
	{ name = "DOWN",  action = 0x00 },
	{ name = "UP",    action = 0x01 },
	{ name = "LEFT",  action = 0x02 },
	{ name = "RIGHT", action = 0x03 },
}

local AVATAR_ADDR_ARCHIPELAGO_SHIFT = 0x284
local MAP_GROUPS_COUNT = 34

-- Where the ghost goes, relative to the player. Two tiles to the left: far enough that it is
-- never confused with the player's own sprite, which is the standing preference for any test
-- ghost, and it keeps the ghost inside the cull window so this test is not measuring culling.
local GHOST_DX = -2
local GHOST_DY = 0

local logfile
local function open_log()
	local dir = "."
	local info = debug.getinfo(1, "S")
	if info and info.source and info.source:sub(1, 1) == "@" then
		dir = info.source:sub(2):match("^(.*)[/\\][^/\\]*$") or "."
	end
	local f = io.open(string.format("%s/spawn_test_%s.log", dir, os.date("%Y%m%d_%H%M%S")), "w")
	if f then logfile = f end
end

local function log(msg)
	console.log(msg)
	if logfile then
		logfile:write(msg, "\n")
		logfile:flush()
	end
end

local function u8(a) return memory.read_u8(a) end
local function s16(a) return memory.read_s16_le(a) end
local function s32(a) return memory.read_s32_le(a) end
local function u32(a) return memory.read_u32_le(a) end
local function mem16(a) return memory.read_u16_le(a) end
local function w8(a, v) memory.write_u8(a, v & 0xff) end
local function w16(a, v) memory.write_u16_le(a, v & 0xffff) end
local function w32(a, v) memory.write_u32_le(a, v & 0xffffffff) end

local addrOffset, addrConfirmed = 0, false

local function playerObjEventExistsAt(base)
	for i = 0, OBJECT_EVENTS_COUNT - 1 do
		local a = base + i * OBJECTEVENT_SIZE
		if (u8(a + 0x02) & 0x1) == 1 and u8(a + 0x08) == 0xff and u8(a + 0x0a) < MAP_GROUPS_COUNT then
			return true
		end
	end
	return false
end

local function tryDetect()
	if playerObjEventExistsAt(GOBJECTEVENTS_ADDR) then
		addrOffset, addrConfirmed = 0, true
	elseif playerObjEventExistsAt(GOBJECTEVENTS_ADDR + AVATAR_ADDR_ARCHIPELAGO_SHIFT) then
		addrOffset, addrConfirmed = AVATAR_ADDR_ARCHIPELAGO_SHIFT, true
	end
end

local function objAddr(i) return GOBJECTEVENTS_ADDR + addrOffset + i * OBJECTEVENT_SIZE end
local function sprAddr(i) return GSPRITES_ADDR + i * SPRITE_SIZE end

local function inOverworld()
	local cb = u32(GMAIN_CALLBACK2_ADDR)
	return cb == CB2_OVERWORLD_ADDR or cb == CB2_OVERWORLD_ADDR + 1
		or cb == CB2_OVERWORLD_ARCHIPELAGO_ADDR or cb == CB2_OVERWORLD_ARCHIPELAGO_ADDR + 1
end

local function playerObjectEventId()
	return u8(GPLAYERAVATAR_ADDR + addrOffset + 0x05)
end

local function describeObj(i)
	local a = objAddr(i)
	local b0, b1 = u8(a + 0x00), u8(a + 0x01)
	return string.format(
		"obj %2d: active=%d gfx=%3d move=%3d localId=%3d map=%d/%-3d cur=(%3d,%3d) init=(%3d,%3d) "
			.. "elev=%d face=%d action=%3d held=%d spriteId=%3d invis=%d offscr=%d",
		i, b0 & 0x01, u8(a + 0x05), u8(a + 0x06), u8(a + 0x08), u8(a + 0x0a), u8(a + 0x09),
		s16(a + 0x10), s16(a + 0x12), s16(a + 0x0c), s16(a + 0x0e), u8(a + 0x0b) & 0x0f,
		u8(a + 0x18) & 0x0f, u8(a + 0x1c), (b0 >> 6) & 0x01, u8(a + 0x04),
		(b1 >> 5) & 0x01, (b1 >> 6) & 0x01)
end

local function describeSpr(i)
	local a = sprAddr(i)
	return string.format(
		"spr %2d: inUse=%d pos=(%4d,%4d) off=(%3d,%3d) anim=%2d cmdIdx=%d data0=%3d data2=%3d "
			.. "subpri=%3d cb=0x%08X invis=%d hFlip=%d attr1=0x%04X matrixNum=%2d(oamHFlip=%d) "
			.. "attr0=0x%04X affine=%d",
		i, u8(a + 0x3e) & 0x01, s16(a + 0x20), s16(a + 0x22), s16(a + 0x24), s16(a + 0x26),
		u8(a + 0x2a), u8(a + 0x2b), s16(a + 0x2e), s16(a + 0x32), u8(a + 0x43), u32(a + 0x1c),
		(u8(a + 0x3e) >> 2) & 0x01, u8(a + 0x3f) & 0x01,
		-- OamData (include/sprite.h): attr1 holds x:9, matrixNum:5, size:2. With affineMode off,
		-- matrixNum bit 3 IS the hardware hFlip -- SetSpriteOamFlipBits (sprite.c:1246) writes
		-- animCmd.hFlip XOR sprite->hFlip there. East is west + .hFlip = TRUE
		-- (object_event_anims.h:196), so this bit is the whole difference between the two.
		mem16(a + 0x02), (mem16(a + 0x02) >> 9) & 0x1f, (mem16(a + 0x02) >> 12) & 0x01,
		mem16(a + 0x00), (mem16(a + 0x00) >> 8) & 0x03)
end

-- ---------------------------------------------------------------------------------------------
-- The spawn itself
-- ---------------------------------------------------------------------------------------------

local function findFreeObjectSlot()
	for i = 0, OBJECT_EVENTS_COUNT - 1 do
		if (u8(objAddr(i) + 0x00) & 0x01) == 0 then return i end
	end
	return nil
end

local function findFreeSpriteSlot()
	-- Scan downward: the engine's own CreateSprite takes the lowest free index, so taking a high
	-- one keeps our ghost out of the way of whatever the game allocates next.
	for i = MAX_SPRITES - 1, 0, -1 do
		if (u8(sprAddr(i) + 0x3e) & 0x01) == 0 then return i end
	end
	return nil
end

local function findFreeLocalId()
	-- Local ids identify an object event within its map. Picking one no live object uses avoids
	-- colliding with a real NPC's identity (and with whatever script is attached to it).
	local used = {}
	for i = 0, OBJECT_EVENTS_COUNT - 1 do
		if (u8(objAddr(i) + 0x00) & 0x01) == 1 then used[u8(objAddr(i) + 0x08)] = true end
	end
	for id = 200, 250 do
		if not used[id] then return id end
	end
	return nil
end

-- GetMapCoordsFromSpritePos (event_object_movement.c:4793) followed by the +8 / +16+centerToCorner
-- adjustment TrySetupObjectEventSprite applies. cameraX/cameraY come from
-- GetObjectEventMovingCameraOffset, which is just the SIGN of gFieldCamera.x/y -- so it is zero
-- while the player stands still, which is the only moment this script spawns.
local function spriteScreenPos(mapX, mapY, centerToCornerVecY)
	local sb1 = u32(GSAVEBLOCK1PTR_ADDR)
	local camX = 0
	local fcx = s32(GFIELDCAMERA_X_ADDR)
	if fcx > 0 then camX = 1 elseif fcx < 0 then camX = -1 end
	local camY = 0
	local fcy = s32(GFIELDCAMERA_Y_ADDR)
	if fcy > 0 then camY = 1 elseif fcy < 0 then camY = -1 end

	local x = ((mapX + camX) - s16(sb1 + 0x00)) << 4
	local y = ((mapY + camY) - s16(sb1 + 0x02)) << 4
	x = x - s16(GTOTALCAMERAPIXELOFFSETX_ADDR)
	y = y - s16(GTOTALCAMERAPIXELOFFSETY_ADDR)
	-- centerToCornerVecY is stored as a signed byte; Lua read it unsigned.
	local c2cY = centerToCornerVecY
	if c2cY > 127 then c2cY = c2cY - 256 end
	return x + 8, y + 16 + c2cY
end

local function tileIsAllocated(n)
	return (u8(SSPRITETILEALLOCBITMAP_ADDR + (n // 8)) >> (n % 8)) & 1 == 1
end

local function setTileAllocated(n, on)
	local a = SSPRITETILEALLOCBITMAP_ADDR + (n // 8)
	local v = u8(a)
	if on then v = v | (1 << (n % 8)) else v = v & ~(1 << (n % 8)) end
	w8(a, v)
end

-- A direct imitation of AllocSpriteTiles (sprite.c:702): scan from the reserved count for a run
-- of free tiles, then mark them. Returns the starting tile, or nil when VRAM has no run that big
-- -- which is a real failure mode on a busy map, not a theoretical one, so it is reported rather
-- than assumed away.
local function allocSpriteTiles(tileCount)
	local i = mem16(GRESERVEDSPRITETILECOUNT_ADDR)
	while true do
		while tileIsAllocated(i) do
			i = i + 1
			if i >= TOTAL_OBJ_TILE_COUNT then return nil end
		end
		local start, found = i, 1
		while found ~= tileCount do
			i = i + 1
			if i >= TOTAL_OBJ_TILE_COUNT then return nil end
			if not tileIsAllocated(i) then found = found + 1 else break end
		end
		if found == tileCount then
			for t = start, start + tileCount - 1 do setTileAllocated(t, true) end
			return start
		end
	end
end

local function freeSpriteTiles(start, tileCount)
	for t = start, start + tileCount - 1 do setTileAllocated(t, false) end
end

local function graphicsFrameTileCount(graphicsId)
	local infoPtr = u32(GOBJECTEVENTGRAPHICSINFOPOINTERS_ADDR + graphicsId * 4)
	if infoPtr == 0 then return nil end
	local size = mem16(infoPtr + 0x06)
	if size == 0 then return nil end
	return size // TILE_SIZE_4BPP
end

local ghostObjId, ghostSprId, ghostLocalId = nil, nil, nil
local ghostTileStart, ghostTileCount = nil, nil

local function spawnGhost()
	local playerObjId = playerObjectEventId()
	local pObj = objAddr(playerObjId)
	local playerSprId = u8(pObj + 0x04)

	-- Self-check before writing a single byte: the player's object event and the sprite it names
	-- must agree with each other. sprite.data[0] (sObjEventId) holding the player's own object
	-- event index proves gSprites is where we think it is -- the one thing an address shift could
	-- silently break, and the one that would corrupt a live sprite if wrong.
	if s16(sprAddr(playerSprId) + 0x2e) ~= playerObjId then
		log(string.format("REFUSING TO WRITE: cross-link check failed -- gSprites[%d].data[0]=%d, "
			.. "expected the player's object event id %d. gSprites is not where this script thinks.",
			playerSprId, s16(sprAddr(playerSprId) + 0x2e), playerObjId))
		return false
	end

	local objId = findFreeObjectSlot()
	local sprId = findFreeSpriteSlot()
	local localId = findFreeLocalId()
	if not objId or not sprId or not localId then
		log(string.format("REFUSING TO WRITE: no free slot (object=%s sprite=%s localId=%s).",
			tostring(objId), tostring(sprId), tostring(localId)))
		return false
	end

	local sb1 = u32(GSAVEBLOCK1PTR_ADDR)
	local mapGroup, mapNum = u8(sb1 + 0x04), u8(sb1 + 0x05)
	local gx = s16(pObj + 0x10) + GHOST_DX
	local gy = s16(pObj + 0x12) + GHOST_DY
	local elevation = u8(pObj + 0x0b) & 0x0f
	local graphicsId = u8(pObj + 0x05)

	log(string.format("spawning into object slot %d / sprite slot %d, localId %d, at map coords "
		.. "(%d,%d) [player is at (%d,%d)], gfx=%d elev=%d",
		objId, sprId, localId, gx, gy, s16(pObj + 0x10), s16(pObj + 0x12), graphicsId, elevation))

	-- --- the object event -------------------------------------------------------------------
	-- ClearObjectEvent zeroes the struct; then exactly the fields InitObjectEventStateFromTemplate
	-- sets, with movementType forced to NONE so nothing drives the ghost but us.
	local a = objAddr(objId)
	for off = 0, OBJECTEVENT_SIZE - 1 do w8(a + off, 0) end
	w8(a + 0x00, 0x05)              -- active (bit0) | triggerGroundEffectsOnMove (bit2)
	w8(a + 0x05, graphicsId)
	w8(a + 0x06, MOVEMENT_TYPE_NONE)
	w8(a + 0x08, localId)
	w8(a + 0x09, mapNum)
	w8(a + 0x0a, mapGroup)
	w8(a + 0x0b, elevation | (elevation << 4)) -- currentElevation | previousElevation
	w16(a + 0x0c, gx) w16(a + 0x0e, gy)        -- initialCoords
	w16(a + 0x10, gx) w16(a + 0x12, gy)        -- currentCoords
	w16(a + 0x14, gx) w16(a + 0x16, gy)        -- previousCoords
	w8(a + 0x18, DIR_SOUTH | (DIR_SOUTH << 4)) -- facingDirection | movementDirection
	w8(a + 0x20, DIR_SOUTH)                    -- previousMovementDirection
	w8(a + 0x04, sprId)

	-- --- the sprite -------------------------------------------------------------------------
	-- Copy the player's sprite wholesale for its four ROM pointers, OAM shape and palette, then
	-- patch the fields that must differ.
	local src, dst = sprAddr(playerSprId), sprAddr(sprId)
	for off = 0, SPRITE_SIZE - 1 do w8(dst + off, u8(src + off)) end

	-- Give the ghost its own VRAM tiles instead of the player's. Without this the ghost shows the
	-- player's current animation frame, because both sprites name the same tiles -- confirmed live
	-- 2026-08-18, and it looked exactly like the ghost copying the player's facing.
	local tileCount = graphicsFrameTileCount(graphicsId)
	if not tileCount then
		log(string.format("REFUSING TO WRITE: no graphics info for graphicsId %d.", graphicsId))
		return false
	end
	local tileStart = allocSpriteTiles(tileCount)
	if not tileStart then
		log(string.format("REFUSING TO WRITE: no run of %d free OBJ tiles available.", tileCount))
		return false
	end
	ghostTileStart, ghostTileCount = tileStart, tileCount
	-- OamData attr2 (u16 at +0x04): tileNum:10, priority:2, paletteNum:4. Only the tile number
	-- changes; priority and palette stay as copied from the player.
	local attr2 = mem16(dst + 0x04)
	w16(dst + 0x04, (attr2 & 0xfc00) | (tileStart & 0x03ff))
	log(string.format("  allocated %d OBJ tiles at %d for the ghost (player uses %d)",
		tileCount, tileStart, mem16(src + 0x04) & 0x03ff))

	local c2cY = u8(dst + 0x29)
	local sx, sy = spriteScreenPos(gx, gy, c2cY)
	w32(dst + 0x1c, MOVEMENTTYPE_NONE_CB)
	w16(dst + 0x20, sx) w16(dst + 0x22, sy)
	w16(dst + 0x24, 0) w16(dst + 0x26, 0)  -- x2/y2: no sub-tile offset yet
	for k = 0, 7 do w16(dst + 0x2e + k * 2, 0) end
	w16(dst + 0x2e, objId)                 -- data[0] = sObjEventId, the cross-link back
	w8(dst + 0x2a, 0)                      -- animNum: face south
	w8(dst + 0x2b, 0)                      -- animCmdIndex
	w8(dst + 0x3e, (u8(dst + 0x3e) | 0x03) & ~0x04) -- inUse | coordOffsetEnabled, not invisible
	w8(dst + 0x3f, u8(dst + 0x3f) | 0x04)  -- animBeginning: restart the animation cleanly

	ghostObjId, ghostSprId, ghostLocalId = objId, sprId, localId
	log("  wrote " .. describeObj(objId))
	log("  wrote " .. describeSpr(sprId))
	log(string.format("  (player for comparison) %s", describeObj(playerObjId)))
	log(string.format("  (player for comparison) %s", describeSpr(playerSprId)))
	return true
end

-- Despawn. The ghost now owns a real tile allocation, so despawning MUST return it -- otherwise
-- every re-spawn leaks a run of OBJ VRAM and a long session eventually cannot spawn at all.
-- What this still does not do is imitate RemoveObjectEventInternal
-- (event_object_movement.c:1399) wholesale: that calls DestroySprite, which frees tiles via the
-- sprite's own `images->size`, and getting that wrong frees somebody else's VRAM. Freeing exactly
-- the range we allocated is both simpler and safer.
local function despawnGhost()
	if not ghostObjId then return end
	w8(objAddr(ghostObjId) + 0x00, 0)                        -- active = 0 (clears the flag byte)
	local d = sprAddr(ghostSprId)
	w8(d + 0x3e, u8(d + 0x3e) & ~0x01)                       -- inUse = 0
	w8(d + 0x3f, u8(d + 0x3f))                               -- (flags byte 2 left as-is)
	w8(d + 0x3e, u8(d + 0x3e) | 0x04)                        -- invisible = 1, belt and braces
	if ghostTileStart then
		freeSpriteTiles(ghostTileStart, ghostTileCount)
	end
	log(string.format("despawned ghost (object slot %d, sprite slot %d, %s OBJ tiles at %s)",
		ghostObjId, ghostSprId, tostring(ghostTileCount), tostring(ghostTileStart)))
	ghostObjId, ghostSprId, ghostLocalId = nil, nil, nil
	ghostTileStart, ghostTileCount = nil, nil
end

-- Liveness by IDENTITY, never by slot state. "The slot is still active" and "my ghost is still
-- there" are different claims: a map load clears the array and the next map's own NPCs take the
-- same slots, which would answer "active?" perfectly plausibly. Crystal produced exactly that
-- false positive and lost a whole run to it. Checking localId and map as well is what makes this
-- an answer about OUR object.
local function ghostAlive()
	if not ghostObjId then return false end
	local a = objAddr(ghostObjId)
	local sb1 = u32(GSAVEBLOCK1PTR_ADDR)
	if sb1 == 0 then return false end
	return (u8(a + 0x00) & 0x01) == 1
		and u8(a + 0x08) == ghostLocalId
		and u8(a + 0x0a) == u8(sb1 + 0x04)
		and u8(a + 0x09) == u8(sb1 + 0x05)
end

local function requestStep(action)
	-- ObjectEventSetHeldMovement (event_object_movement.c:4870): three object fields plus the
	-- sprite's action-function index reset. The engine plays out the rest of the tile.
	local a = objAddr(ghostObjId)
	w8(a + 0x1c, action)
	local b0 = u8(a + 0x00)
	b0 = (b0 | 0x40) & ~0x80 -- heldMovementActive = 1, heldMovementFinished = 0
	w8(a + 0x00, b0)
	w16(sprAddr(ghostSprId) + 0x32, 0) -- data[2] = sActionFuncId
end

-- ---------------------------------------------------------------------------------------------
-- Phases. A countdown, never a window to hit: the run asks for endurance, not timing.
-- ---------------------------------------------------------------------------------------------

open_log()
log("=== MeshGhost Emerald spawn test 1 (WRITES GAME RAM -- live only, no save touched) ===")
log("Stand still in the overworld with clear ground two tiles to your LEFT.")

if not memory.usememorydomain("System Bus") then
	log("FATAL: could not select the System Bus memory domain.")
	return
end

local PHASE_READY = 300     -- 5s of preconditions before anything is written
local PHASE_OBSERVE = 300   -- 5s watching the spawned ghost sit
local PHASE_WALK = 240      -- 4s: one step left, then one step down

local frames, phaseFrames = 0, 0
local phase = "wait"
local lastReport = 0
local walkIssued = 0

local function tick()
	frames = frames + 1

	if not addrConfirmed then
		tryDetect()
		if not addrConfirmed then return end
		if addrOffset ~= 0 then
			log("REFUSING TO WRITE: this is an Archipelago-shifted ROM. Spawn test 1 is vanilla-only "
				.. "by design -- see the ADR's Archipelago condition. Nothing was written.")
			phase = "refused"
			return
		end
		log("ROM variant: vanilla. Addresses confirmed by finding the player's own object event.")
	end

	if phase == "refused" or phase == "done" then return end

	if not inOverworld() then
		if frames - lastReport >= 300 then
			log(string.format("[%6d] waiting: not in the overworld yet.", frames))
			lastReport = frames
		end
		return
	end

	phaseFrames = phaseFrames + 1

	-- The engine clears every object event on a map load (RemoveAllObjectEventsExceptPlayer), and
	-- culls anything that leaves the window around the player -- so a ghost is expected to die,
	-- repeatedly, and re-spawning is normal operation rather than error handling.
	if (phase == "observe" or phase == "walk" or phase == "cycle") and not ghostAlive() then
		log(string.format("[%6d] ghost is gone (map load or cull). Re-spawning.", frames))
		ghostObjId, ghostSprId, ghostLocalId = nil, nil, nil
		if spawnGhost() then
			phase, phaseFrames = "cycle", 0
		else
			phase = "refused"
		end
		return
	end

	if phase == "wait" then
		phase, phaseFrames = "ready", 0
		log("--- phase 1: preconditions (5 seconds) ---")

	elseif phase == "ready" then
		if phaseFrames % 60 == 0 then
			local secs = (PHASE_READY - phaseFrames) // 60
			local objId, sprId = findFreeObjectSlot(), findFreeSpriteSlot()
			log(string.format("[%6d] spawning in %d... free object slot=%s free sprite slot=%s",
				frames, secs, tostring(objId), tostring(sprId)))
			log("        " .. describeObj(playerObjectEventId()))
		end
		if phaseFrames >= PHASE_READY then
			log("--- phase 2: writing the ghost ---")
			if spawnGhost() then
				phase, phaseFrames = "observe", 0
				log("--- phase 3: watching it for 15 seconds (it should be standing to your left) ---")
			else
				phase = "refused"
			end
		end

	elseif phase == "observe" then
		-- Read back what the ENGINE owns, not what we wrote: the sprite position it maintains as
		-- the camera moves, and whether the object is still active at all. An echo of our own
		-- write would prove only that the write landed.
		if phaseFrames % 60 == 0 then
			log(string.format("[%6d] %s", frames, describeObj(ghostObjId)))
			log(string.format("         %s", describeSpr(ghostSprId)))
		end
		if phaseFrames >= PHASE_OBSERVE then
			phase, phaseFrames, walkIssued = "walk", 0, 0
			log("--- phase 4: asking the engine to walk it one tile LEFT, then one tile DOWN ---")
		end

	elseif phase == "walk" then
		if walkIssued == 0 then
			requestStep(MOVEMENT_ACTION_WALK_NORMAL_LEFT)
			walkIssued = 1
			log(string.format("[%6d] requested WALK_NORMAL_LEFT", frames))
		elseif walkIssued == 1 and phaseFrames >= 120 then
			requestStep(MOVEMENT_ACTION_WALK_NORMAL_DOWN)
			walkIssued = 2
			log(string.format("[%6d] requested WALK_NORMAL_DOWN", frames))
		end
		if phaseFrames % 8 == 0 then
			log(string.format("[%6d] %s", frames, describeObj(ghostObjId)))
			log(string.format("         %s", describeSpr(ghostSprId)))
		end
		if phaseFrames >= PHASE_WALK then
			phase, phaseFrames = "cycle", 0
			log("--- phase 5: facing cycle. The ghost turns DOWN, UP, LEFT, RIGHT, 3s each, on ---")
			log("    repeat, announced in this log before each turn. Say which ones look wrong.")
		end

	elseif phase == "cycle" then
		-- One deliberate turn every 3 seconds, named in the log BEFORE it happens, looping
		-- forever: the run asks for endurance, not timing, and every direction gets many
		-- chances rather than one moment to catch.
		if phaseFrames % 180 == 1 then
			local step = (phaseFrames // 180) % #FACE_ACTIONS + 1
			local f = FACE_ACTIONS[step]
			requestStep(f.action)
			log(string.format("[%6d] turning to face %s (action 0x%02X)", frames, f.name, f.action))
		end
		if phaseFrames % 180 == 60 then -- read back a second later, once the turn has played out
			log(string.format("         %s", describeObj(ghostObjId)))
			log(string.format("         %s", describeSpr(ghostSprId)))
			-- The player's own sprite, same frame, as the control. The player renders every
			-- direction correctly by definition, so any field that differs between these two
			-- lines while the ghost renders wrong is the cause -- and any field that matches
			-- rules itself out. Comparing against the thing that works beats reasoning about
			-- the thing that does not.
			local pObjId = playerObjectEventId()
			log(string.format("  PLAYER %s", describeObj(pObjId)))
			log(string.format("  PLAYER %s", describeSpr(u8(objAddr(pObjId) + 0x04))))
		end
	end
end

MESHGHOST_DEV_TICK = tick
MESHGHOST_DEV_UNLOAD = function()
	-- Leaving a ghost behind on a script swap would stack a second one on the next load, and
	-- nothing in the game would ever clean it up.
	pcall(despawnGhost)
	if logfile then logfile:close() logfile = nil end
end

if not MESHGHOST_DEV_LOADER then
	while true do
		local ok, err = pcall(tick)
		if not ok then log("spawn test error: " .. tostring(err)) end
		emu.frameadvance()
	end
end
